name = "gaudis-crypt"
version = "0.1.0"
keywords = ["math", "cryptography", "formalization"]
defaultTargets = ["GaudisCrypt"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
# TODO: re-enable this (remove the line) once files have proper copyright headers
weak.linter.style.header = false
maxSynthPendingDepth = 3

[[require]]
name = "Metatheory-Unruh"
git = "https://github.com/dominique-unruh/Lean-Metatheory.git"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.31.0"

[[lean_lib]]
name = "GaudisCrypt"

[[lean_lib]]
# Used only by the local GitHub Pages build script (`scripts/build-gh-pages.py`).
# The corresponding `DocEntrypoint.lean` file is generated and deleted by the script.
name = "DocEntrypoint"
srcDir = "."
